### ISSUE TITLE
Exercism fetch does not pull secret-handshake

### ISSUE THREAD

**Issue by fluxusfrequency** [exercism/xpython#131]
From the CLI, if I have an empty secret-handshake folder and run `exercism fetch`, the test is not populated. `exercism fetch python secret-handhake` does work, though. Not sure if this is a CLI or xpython issue.

**Comment by sjakobi** [comment]
Are there any updates on this issue, @fluxusfrequency + @kytrinyx?

Otherwise I'd like to close this because it doesn't seem to be related to xpython specifically.

**Comment by fluxusfrequency** [comment]
I have nothing to add, but go ahead and close it if you like. Seems like a CLI issue?

**Comment by kytrinyx** [comment]
I lost track of this one, but it's probably an API issue rather than a CLI one. I'm going to open a new ticket for it in the exercism.io repo.
