### ISSUE TITLE
Overhaul the Ocr Numbers exercise

### ISSUE THREAD

**Issue by sjakobi** [exercism/xpython#138]
The current test suite is pretty rudimentary compared to those on other language tracks like [Go](https://github.com/exercism/xgo/blob/master/ocr-numbers/ocr_numbers_test.go) or [Haskell](https://github.com/exercism/xhaskell/blob/master/ocr-numbers/ocr-numbers_test.hs).

Also, the ASCII numbers in the test suite should be well formatted.

There's some discussion regarding the exercise here: https://github.com/exercism/xpython/pull/137

**Comment by outkaj** [comment]
It looks from #137 like the exercise was updated to some degree, but that you still want some cleanup and expansion of the test suite. If that's still the case, I can take a look at it.

**Comment by kytrinyx** [comment]
That would be lovely, thanks!

**Comment by behrtam** [comment]
Can this be closed because #173 did expand the test suite for ocr-numbers sufficiently?

**Comment by kytrinyx** [comment]
Yepp, good call.
