### ISSUE TITLE
gigasecond: use times (not dates) for inputs and outputs

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xpython#163]
A duration of a gigasecond should be measured in seconds, not
days.

The `gigasecond` problem has been implemented in a number of languages,
and this issue has been generated for each of these language tracks.
This may already be fixed in this track, if so, please make a note of it
and close the issue.

There has been some discussion about whether or not gigaseconds should
take daylight savings time into account, and the conclusion was "no", since
not all locations observe daylight savings time.

**Comment by Dog** [comment]
I can confirm the issue exists in xpython. I'm working on a fix now.
