### ISSUE TITLE
Inconsistency in Python Test for Bob Exercise

### ISSUE THREAD

**Issue by ishan-marikar** [exercism/xpython#184]
I was going coding through the exercises and I noticed that I couldn't really pass a certain test:

``` python
     def test_calmly_speaking_with_umlauts(self):
        self.assertEqual(
        'Whatever.', bob.hey('ÜMLäÜTS!')
    )
```

The code that I used:
``` python
    if what.isupper() or what[-1:] == "!" : 
        return "Whoa, chill out!"
```

According to the readme, if we yell at him (assuming that by yelling, you mean that the input either ends with an exclamation mark or is in upper case), Bob should respond with 'Whoa, chill out!'. Seeing as the input for the above test both contains uppercase letters and an exclamation mark, I don't understand why the expected response would be 'Whatever.'.

.. anyways, @kytrinyx,  I really like the Exercism project and your book. Wish you all the best c:

**Comment by kytrinyx** [comment]
Thanks @ishan-marikar :)

Are there any tests that define that an exclamation point means shouting?

**Comment by ishan-marikar** [comment]
``` python
def test_shouting(self):
        self.assertEqual(
            'Whoa, chill out!',
            bob.hey('WATCH OUT!')
        )

def test_shouting_numbers(self):
        self.assertEqual(
            'Whoa, chill out!', bob.hey('1, 2, 3 GO!')
        )

def test_shouting_with_special_characters(self):
        self.assertEqual(
            'Whoa, chill out!',
            bob.hey('ZOMG THE %^*@#$(*^ ZOMBIES ARE COMING!!11!!1!')
        )

```

I went through the test code and noticed that every sentence that included the exclamation mark was in the upper case, so I guess it might have been incorrect to assume that. .-.
