### ISSUE TITLE
Ignore all tests except the first one by default

### ISSUE THREAD

**Issue by Ben-Baert** [exercism/xpython#189]
It'd be useful to have unittest.SkipTest decorators that ignores all but the first test. This way, you can try to make the first test work, once it works, delete the next unittest.SkipTest decorator, make the code pass that test, etc., instead of being overloaded by a barrage of tests that fail. 

I've noticed that this approach seems to be used in some language tracks (e.g. Rust), but it'd be useful if this was standard in all tracks. I now do this manually, but it'd be nice if this was implemented as standard. Another approach is to group tests that test similar functionality together (ie. different testcase classes), and then ignore all but the first class. That way, you don't get error messages concerning functionality that you're not yet trying to deal with.

**Comment by Dog** [comment]
We have documentation for that workflow, but it doesn't seem to have been pushed to the live site.

You can find the documentation here:
https://github.com/exercism/xpython/blob/master/docs/WORKFLOW.md

@kytrinyx How do I get this change pushed to live?

**Comment by kytrinyx** [comment]
At the moment the documentation is half-way between two systems. It needs to be in the docs site to go live. I'll copy it over.

**Comment by kytrinyx** [comment]
I'm deploying https://github.com/exercism/docs/commit/56020d8e7f4a599c3c92c7ebba0f8c95ca3538e6 now.

**Comment by Dog** [comment]
@kytrinyx Thanks. I consider this issue closed then. If not, please reopen.
