### ISSUE TITLE
Font size perhaps too big in <blockquote>

### ISSUE THREAD

**Issue by Peque** [exercism/xpython#204]
I think the quoted text should have similar (if not the same) size to the rest of the text in the nitpicks. See the image bellow:

![blockquote](https://cloud.githubusercontent.com/assets/526577/9746744/ef132f9e-5679-11e5-9808-aab8568d1817.png)

Instead, it could be a little gray and/or in italics and/or with a different background color.

**Comment by kytrinyx** [comment]
Agreed.

**Comment by Peque** [comment]
Font resized
----------
![00](https://cloud.githubusercontent.com/assets/526577/9747165/6387b9b0-567c-11e5-859d-4e684e7e0680.png)

Font resized + italic + gray
----------
![02](https://cloud.githubusercontent.com/assets/526577/9747167/64cfa238-567c-11e5-98cb-65c942f58f2e.png)

Font resized + background color
----------
![03](https://cloud.githubusercontent.com/assets/526577/9747296/30702142-567d-11e5-9eab-a4604492b43e.png)

**Comment by Peque** [comment]
I personally prefer the second or the third alternative. :stuck_out_tongue_winking_eye: 

BTW: I just noticed I created this issue in `xpython` rather than in `exercism.io`. I should probably have posted this there, right? Do you want me to close this and reopen it there?

**Comment by kytrinyx** [comment]
Ah, I didn't notice that this was in xpython. Yeah, if you wouldn't mind re-opening it in exercism.io that would be great.

I like the middle suggestion best.

**Comment by Peque** [comment]
Issue re-opened: https://github.com/exercism/exercism.io/issues/2521
