### ISSUE TITLE
Grade School False Positives

### ISSUE THREAD

**Issue by Dog** [exercism/xpython#208]
I believe we could better catch false positives on this exercise with inspect.

https://docs.python.org/2/library/inspect.html#inspect.isgenerator

**Comment by kytrinyx** [comment]
Do you have specific examples of false positives that the current test suite isn't catching?

**Comment by Dog** [comment]
The problem is that if the user uses a structure that is unordered, they may get lucky and pass the suite.
https://github.com/exercism/xpython/issues/151

I wrote this as a reminder to investigate if inspect may allow us to better handle the case. Right now we check if they use a generator, sequence, or a class which implements the python magic method `__reversed__` to check if they are using an ordered structure.

**Comment by kytrinyx** [comment]
Ah, right. That makes sense. Thanks for clarifying.

**Comment by behrtam** [comment]
Is there a real difference between for example `isinstance(foo, types.GeneratorType)` or `inspect.isgenerator(foo)`?

**Comment by Dog** [comment]
I looked into the source and found that `inspect.isgenerator(foo)` actually calls `isinstance(foo, types.GeneratorType)`

https://hg.python.org/cpython/file/2.7/Lib/inspect.py#l179
