### ISSUE TITLE
Add missing stub/skeleton files

### ISSUE THREAD

**Issue by behrtam** [exercism/xpython#210]
I only worked on the *Python* and *Go* track and I noticed a small difference. In the go track (at least for the first 5 problems) there are always stub files, while in the python track there are only stub files for `hello-world` and `bob`.
Maybe there shouldn't be stub files for all exercises, but at least for most of them and definitely for the first exercises. It would make the start easier and support TDD, because there wouldn't be `ImportError: No module named <exercise>` if you try to directly run the tests.

**Comment by kytrinyx** [comment]
We had a few discussions in the Go track about how many stub files to support, and our answer (a small handful, not too many) was kind of arbitrary, but so far it seems to have worked out.

**Comment by behrtam** [comment]
I had a closer look into the `xgo` repo and saw even there only ~20% of the exercises have stub files. If I understand the `xruby` repo correct they don't have stub files at all.

So, I think this issue should be closed.

**Comment by kytrinyx** [comment]
Yepp, agreed.
