### ISSUE TITLE
Make all exercises PEP8 compliant except line length

### ISSUE THREAD

**Issue by behrtam** [exercism/xpython#214]
I would like to make all exercises PEP8 compliant except line length (E501) like I already did with the `secret-handshake` 14b726c. Now I am not sure what's the best way to do this. With one pull request for all or a single pull request per exercise that is not compliant.

Exercises with 5 problems on average: [~~'wordy'~~, ~~'word-count'~~, ~~'poker'~~, ~~'simple-cipher'~~, 'nucleotide-count', ~~'nth-prime'~~, ~~'ocr-numbers'~~, ~~'house'~~, 'sublist', 'pythagorean-triplet', ~~'roman-numerals'~~, ~~'meetup'~~, 'strain', ~~'saddle-points'~~, 'secret-handshake', ~~'minesweeper'~~, 'accumulate', 'triangle', ~~'bob'~~, 'pascals-triangle', ~~'phone-number'~~]

**Comment by Dog** [comment]
I would prefer it was submitted per exercise, with the commit message prepending the exercise.

Something like:

wordy: PEP8 Compliance Updated

**Comment by behrtam** [comment]
The end is in sight.🏁

**Comment by Dog** [comment]
Has this issue been completed?

**Comment by behrtam** [comment]
Just created the last 4 pull requests.
