### ISSUE TITLE
word_count: test mixed case

### ISSUE THREAD

**Issue by behrtam** [exercism/xpython#234]
I just saw a [solution](http://exercism.io/submissions/6f98994392d649f39ce480c3c1886e2f?i=1) to the `word_count` exercise where my feeling was that this shouldn't pass all tests. There is already one mixed case test, but it has a specific word order so that this solution works.

```python
def word_count(input):
    list = {}
    for word in input.split():
        if word in list:
            list[word]+=1
        elif word.lower() in list:
            list[word.lower()]+=1
        else:
            list[word]=1
    return list

>>> word_count('GO go Go')
{'GO': 1, 'go': 2}
>>> word_count('go Go GO')
{'go': 3}
>>>
```

**Comment by Dog** [comment]
The reason for this is that a change was applied to the test to normalize case.

https://github.com/exercism/xpython/commit/0314cbf4d6e6fe4cdf54f3dbf464ddad0cfc1253

It was justified because other language tracks expect normalization - specifically ruby and clojure in the pull request. I also noticed Haskell does this normalization.

**Comment by behrtam** [comment]
The very brief [README](https://github.com/exercism/x-common/blob/master/word-count.md) let's space for all sorts of implementation/speculation. The provided example does not need normalization.
If so many tracks expect normalization why hasn't the minimalistic readme been improved?

My simple solution to the mixed case test is to expand the test string `"go Go GO"` to
`"go Go GO Stop stop"` and assume `"{'go': 3, 'stop': 2}"` as result.

**Comment by kytrinyx** [comment]
I actually don't mind which direction the user normalizes to, and I think that it would be nice to leave that up to the person solving the problem. I like this suggested approach and wouldn't mind changing the other tracks to use it.

**Comment by behrtam** [comment]
Okay, did it for the Python track.
