### ISSUE TITLE
accumulate: Remove deprecation status

### ISSUE THREAD

**Issue by behrtam** [exercism/xpython#245]
The exercise `accumulate` is currently deprecated [config.json#L58](https://github.com/exercism/xpython/blob/master/config.json#L58) and I would like to change that. The only hint to the reason for the deprecation I could find was in the [example.py](https://github.com/exercism/xpython/blob/master/accumulate/example.py#L1).

> `# [op(x) for x in seq] would be nice but trivial`

The [README.md](https://github.com/exercism/x-common/blob/master/accumulate.md) lists `map()` as restricted which leaves us with a for-loop or list comprehension. While this might seam trivial ([`xgo`](https://github.com/exercism/xgo/blob/master/accumulate/example.go#L4-L7) for example looks as trivial) I think we can score two good learning points here.

* Most people who are new to Python don't know list comprehension and will most likely start with a for-loop and receive a nit to look into list comprehension.
* Some people might not know that Python has anonymous functions (`lambda`) which they can discover in the test suite.

If we put this exercise towards the start of the track it might help some people to create simpler solutions for other exercises by applying those two concepts.

**Comment by kytrinyx** [comment]
You make a good argument. @Dog, what do you think? Do you recall any other reasons why we deprecated it?

**Comment by behrtam** [comment]
I did a little digging and it turns out @sjakobi deprecated it. https://github.com/exercism/xpython/commit/bf9b7804a67dce1bbea263ec2fe5cb1fb4af7141#diff-06b2d3b23dce96e1619d2b53d6c947ecR55

**Comment by Dog** [comment]
I am not sure, but I seem to recall it was deprecated for being too easy an assignment.

**Comment by sjakobi** [comment]
Another aspect was my impression that the name of the exercise is rather unfortunate. "Accumulation" is usually understood to be something different than transforming each element of a collection in the same way.
Deprecating the exercise probably wasn't the best solution for that problem though.

**Comment by sjakobi** [comment]
Another aspect was my impression that the name of the exercise is rather unfortunate. "Accumulation" is usually understood to be something different than transforming each element of a collection in the same way.
Deprecating the exercise probably wasn't the best solution for that problem though.

**Comment by kytrinyx** [comment]
I think we should rename the exercise across the board to fix the naming issue. I'll open an issue in the x-common repository.

**Comment by soniakeys** [comment]
Python has itertools.accumulate that does exactly this, right?  I don't know much about functional languages but I would expect a number of them would have a function for this.  If a number of them call it something besides accumulate, maybe that would be a better name.  If not, maybe accumulate is okay.

I thought it was a little strange that the readme makes a special exception for Elixir and Lisp.  Maybe the intent should be that you not call a single function (like itertools.accumulate) but instead implement it somehow as if that single function wasn't available.  The readme might defer to the track test suites for more specific instructions.  In most cases the track test suites would contain some comments saying exactly what function was disallowed but then it would up to nitpickers to call foul when someone used the disallowed function.  Some languages though might have the capability for the test program to explicitly check that the disallowed function wasn't used.

Also there is the list-ops exercise which I think has similar intent.  Should these exercises be combined?

**Comment by Dog** [comment]
I believe this issue can be closed due to the discussion in https://github.com/exercism/x-common/issues/129. Are you alright with that @behrtam ?
