### ISSUE TITLE
word-count: watch acceptance after change

### ISSUE THREAD

**Issue by behrtam** [exercism/xpython#256]
*Not an issue more a mental note.* We should keep an eye on `word-count` now that we have made the split more complicated (#251) and we test unicode (#252). Many linux/mac user might use 2.7 which is not unicode by default.
The task is still pretty easy but maybe not the best 2nd exercise for beginner.

*comments*
http://exercism.io/submissions/2347082298814e2aa721effc72cc3cb7
http://exercism.io/submissions/c4f4b991ff244e1d8d7e4f0c728aa0bd (update problem)

**Comment by behrtam** [comment]
http://exercism.io/submissions/2347082298814e2aa721effc72cc3cb7

**Comment by kytrinyx** [comment]
For what it's worth if we move an exercise farther back, it doesn't affect people who already did the exercise.

**Comment by behrtam** [comment]
While some start with a very hacky first iteration, my feeling is the changes don't make it too complicated.
