### ISSUE TITLE
acronym: implement new exercise

### ISSUE THREAD

**Issue by behrtam** [exercism/xpython#260]
The exercise `acronym` ([md](https://github.com/exercism/x-common/blob/master/acronym.md), [yml](https://github.com/exercism/x-common/blob/master/acronym.yml)) is a very easy one `''.join(word[0].upper() for word in words.split())`. Should we implement it or should we add it to the "foregone" section in the `config.json`.

**Comment by outkaj** [comment]
Why not implement it but with the caveat "your solution can only be 1 or 2 lines" or something similar? This could encourage users who are unfamiliar to learn more about Python's built-in functions and list comprehension support.

**Comment by behrtam** [comment]
Yes why not. Should also be an easy task to figure out how to at new exercises to the python track.
