### ISSUE TITLE
triangle: incorrect test in some tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xpython#298]
Please check if there's a test that states that a triangle with sides 2, 4, 2 is invalid. The triangle inequality states that for any triangle, the sum of the lengths of any two sides must be greater than or equal to the length of the remaining side. If this doesn't affect this track, go ahead and just close the issue.

**Comment by behrtam** [comment]
```python
def test_triangles_violating_triangle_inequality_are_illegal_2(self):
    self.assertRaises(TriangleError, Triangle, 2, 4, 2)
```
I'm not totally sure what to do. Should the test case just be removed or should we test it as "isosceles" instead?

**Comment by kytrinyx** [comment]
Let's test in as isosceles--it's a good edge case to have, I think.

**Comment by behrtam** [comment]
We should wait until this discussion is settled: https://github.com/exercism/xerlang/issues/85

**Comment by kytrinyx** [comment]
Agreed.

**Comment by behrtam** [comment]
So my understanding of the erlang issue is that while `2, 4, 2` is a special triangle (degenerated - basically a line) we will treat it as not a triangle (has no area) to keep this exercise simple. So maybe the x-common description needs to be updated but the python test case can stay as it is.

**Comment by kytrinyx** [comment]
There was a bit of confusion with this issue. I've summarized my current understanding here: https://github.com/exercism/x-common/issues/202

I am closing this issue. If necessary I will open a new issue once we have come to an agreement about how to resolve the inconsistencies and what exact steps to take.
