### ISSUE TITLE
Implement Python exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xpython#3]
Copied from exercism/exercism.io#272 reported by @BrianHicks 

----

This is a placeholder issue for converting ruby/clojure exercises to Python.

(I'm thinking ruby/clojure since Python is a mix of OO and functional, depending on what's most appropriate)

- [x] accumulate (not appropriate) ([md](https://github.com/exercism/x-common/blob/master/accumulate.md), [yml](https://github.com/exercism/x-common/blob/master/accumulate.yml))
- [x] anagram ([md](https://github.com/exercism/x-common/blob/master/anagram.md), [yml](https://github.com/exercism/x-common/blob/master/anagram.yml))
- [x] beer-song ([md](https://github.com/exercism/x-common/blob/master/beer-song.md), [yml](https://github.com/exercism/x-common/blob/master/beer-song.yml))
- [x] binary ([md](https://github.com/exercism/x-common/blob/master/binary.md), [yml](https://github.com/exercism/x-common/blob/master/binary.yml))
- [x] bob ([md](https://github.com/exercism/x-common/blob/master/bob.md), [yml](https://github.com/exercism/x-common/blob/master/bob.yml))
- [x] difference-of-squares ([md](https://github.com/exercism/x-common/blob/master/difference-of-squares.md), [yml](https://github.com/exercism/x-common/blob/master/difference-of-squares.yml))
- [x] etl ([md](https://github.com/exercism/x-common/blob/master/etl.md), [yml](https://github.com/exercism/x-common/blob/master/etl.yml))
- [x] gigasecond ([md](https://github.com/exercism/x-common/blob/master/gigasecond.md), [yml](https://github.com/exercism/x-common/blob/master/gigasecond.yml))
- [x] grade-school ([md](https://github.com/exercism/x-common/blob/master/grade-school.md), [yml](https://github.com/exercism/x-common/blob/master/grade-school.yml))
- [x] grains ([md](https://github.com/exercism/x-common/blob/master/grains.md), [yml](https://github.com/exercism/x-common/blob/master/grains.yml))
- [x] kindergarten-garden ([md](https://github.com/exercism/x-common/blob/master/kindergarten-garden.md), [yml](https://github.com/exercism/x-common/blob/master/kindergarten-garden.yml))
- [x] largest-series-product ([md](https://github.com/exercism/x-common/blob/master/largest-series-product.md), [yml](https://github.com/exercism/x-common/blob/master/largest-series-product.yml))
- [x] leap ([md](https://github.com/exercism/x-common/blob/master/leap.md), [yml](https://github.com/exercism/x-common/blob/master/leap.yml))
- [x] luhn ([md](https://github.com/exercism/x-common/blob/master/luhn.md), [yml](https://github.com/exercism/x-common/blob/master/luhn.yml))
- [x] matrix ([md](https://github.com/exercism/x-common/blob/master/matrix.md), [yml](https://github.com/exercism/x-common/blob/master/matrix.yml))
- [x] meetup (not appropriate) ([md](https://github.com/exercism/x-common/blob/master/meetup.md), [yml](https://github.com/exercism/x-common/blob/master/meetup.yml))
- [x] nth-prime ([md](https://github.com/exercism/x-common/blob/master/nth-prime.md), [yml](https://github.com/exercism/x-common/blob/master/nth-prime.yml))
- [x] nucleotide-count ([md](https://github.com/exercism/x-common/blob/master/nucleotide-count.md), [yml](https://github.com/exercism/x-common/blob/master/nucleotide-count.yml))
- [x] octal ([md](https://github.com/exercism/x-common/blob/master/octal.md), [yml](https://github.com/exercism/x-common/blob/master/octal.yml))
- [x] palindrome-products ([md](https://github.com/exercism/x-common/blob/master/palindrome-products.md), [yml](https://github.com/exercism/x-common/blob/master/palindrome-products.yml))
- [x] phone-number ([md](https://github.com/exercism/x-common/blob/master/phone-number.md), [yml](https://github.com/exercism/x-common/blob/master/phone-number.yml))
- [x] pig-latin ([md](https://github.com/exercism/x-common/blob/master/pig-latin.md), [yml](https://github.com/exercism/x-common/blob/master/pig-latin.yml))
- [x] point-mutations ([md](https://github.com/exercism/x-common/blob/master/point-mutations.md), [yml](https://github.com/exercism/x-common/blob/master/point-mutations.yml))
- [x] prime-factors ([md](https://github.com/exercism/x-common/blob/master/prime-factors.md), [yml](https://github.com/exercism/x-common/blob/master/prime-factors.yml))
- [x] raindrops ([md](https://github.com/exercism/x-common/blob/master/raindrops.md), [yml](https://github.com/exercism/x-common/blob/master/raindrops.yml))
- [x] rna-transcription ([md](https://github.com/exercism/x-common/blob/master/rna-transcription.md), [yml](https://github.com/exercism/x-common/blob/master/rna-transcription.yml))
- [x] robot-name ([md](https://github.com/exercism/x-common/blob/master/robot-name.md), [yml](https://github.com/exercism/x-common/blob/master/robot-name.yml))
- [x] roman-numerals ([md](https://github.com/exercism/x-common/blob/master/roman-numerals.md), [yml](https://github.com/exercism/x-common/blob/master/roman-numerals.yml))
- [x] scrabble-score ([md](https://github.com/exercism/x-common/blob/master/scrabble-score.md), [yml](https://github.com/exercism/x-common/blob/master/scrabble-score.yml))
- [x] series ([md](https://github.com/exercism/x-common/blob/master/series.md), [yml](https://github.com/exercism/x-common/blob/master/series.yml))
- [x] sieve ([md](https://github.com/exercism/x-common/blob/master/sieve.md), [yml](https://github.com/exercism/x-common/blob/master/sieve.yml))
- [x] space-age ([md](https://github.com/exercism/x-common/blob/master/space-age.md), [yml](https://github.com/exercism/x-common/blob/master/space-age.yml))
- [x] strain (not appropriate) ([md](https://github.com/exercism/x-common/blob/master/strain.md), [yml](https://github.com/exercism/x-common/blob/master/strain.yml))
- [x] sum-of-multiples ([md](https://github.com/exercism/x-common/blob/master/sum-of-multiples.md), [yml](https://github.com/exercism/x-common/blob/master/sum-of-multiples.yml))
- [x] triangle ([md](https://github.com/exercism/x-common/blob/master/triangle.md), [yml](https://github.com/exercism/x-common/blob/master/triangle.yml))
- [x] word-count ([md](https://github.com/exercism/x-common/blob/master/word-count.md), [yml](https://github.com/exercism/x-common/blob/master/word-count.yml))
- [ ] allergies ([md](https://github.com/exercism/x-common/blob/master/allergies.md), [yml](https://github.com/exercism/x-common/blob/master/allergies.yml))
- [ ] atbash-cipher ([md](https://github.com/exercism/x-common/blob/master/atbash-cipher.md), [yml](https://github.com/exercism/x-common/blob/master/atbash-cipher.yml))
- [ ] bank-account ([md](https://github.com/exercism/x-common/blob/master/bank-account.md), [yml](https://github.com/exercism/x-common/blob/master/bank-account.yml))
- [ ] binary-search ([md](https://github.com/exercism/x-common/blob/master/binary-search.md), [yml](https://github.com/exercism/x-common/blob/master/binary-search.yml))
- [ ] binary-search-tree ([md](https://github.com/exercism/x-common/blob/master/binary-search-tree.md), [yml](https://github.com/exercism/x-common/blob/master/binary-search-tree.yml))
- [ ] bottles ([md](https://github.com/exercism/x-common/blob/master/bottles.md), [yml](https://github.com/exercism/x-common/blob/master/bottles.yml))
- [ ] clock ([md](https://github.com/exercism/x-common/blob/master/clock.md), [yml](https://github.com/exercism/x-common/blob/master/clock.yml))
- [ ] crypto-square ([md](https://github.com/exercism/x-common/blob/master/crypto-square.md), [yml](https://github.com/exercism/x-common/blob/master/crypto-square.yml))
- [ ] custom-set ([md](https://github.com/exercism/x-common/blob/master/custom-set.md), [yml](https://github.com/exercism/x-common/blob/master/custom-set.yml))
- [ ] dot-dsl ([md](https://github.com/exercism/x-common/blob/master/dot-dsl.md), [yml](https://github.com/exercism/x-common/blob/master/dot-dsl.yml))
- [ ] food-chain ([md](https://github.com/exercism/x-common/blob/master/food-chain.md), [yml](https://github.com/exercism/x-common/blob/master/food-chain.yml))
- [ ] forth ([md](https://github.com/exercism/x-common/blob/master/forth.md), [yml](https://github.com/exercism/x-common/blob/master/forth.yml))
- [ ] go-counting ([md](https://github.com/exercism/x-common/blob/master/go-counting.md), [yml](https://github.com/exercism/x-common/blob/master/go-counting.yml))
- [ ] hamming ([md](https://github.com/exercism/x-common/blob/master/hamming.md), [yml](https://github.com/exercism/x-common/blob/master/hamming.yml))
- [ ] hexadecimal ([md](https://github.com/exercism/x-common/blob/master/hexadecimal.md), [yml](https://github.com/exercism/x-common/blob/master/hexadecimal.yml))
- [ ] house ([md](https://github.com/exercism/x-common/blob/master/house.md), [yml](https://github.com/exercism/x-common/blob/master/house.yml))
- [ ] linked-list ([md](https://github.com/exercism/x-common/blob/master/linked-list.md), [yml](https://github.com/exercism/x-common/blob/master/linked-list.yml))
- [ ] list-ops ([md](https://github.com/exercism/x-common/blob/master/list-ops.md), [yml](https://github.com/exercism/x-common/blob/master/list-ops.yml))
- [ ] minesweeper ([md](https://github.com/exercism/x-common/blob/master/minesweeper.md), [yml](https://github.com/exercism/x-common/blob/master/minesweeper.yml))
- [ ] ocr-numbers ([md](https://github.com/exercism/x-common/blob/master/ocr-numbers.md), [yml](https://github.com/exercism/x-common/blob/master/ocr-numbers.yml))
- [ ] parallel-letter-frequency ([md](https://github.com/exercism/x-common/blob/master/parallel-letter-frequency.md), [yml](https://github.com/exercism/x-common/blob/master/parallel-letter-frequency.yml))
- [ ] pascals-triangle ([md](https://github.com/exercism/x-common/blob/master/pascals-triangle.md), [yml](https://github.com/exercism/x-common/blob/master/pascals-triangle.yml))
- [ ] proverb ([md](https://github.com/exercism/x-common/blob/master/proverb.md), [yml](https://github.com/exercism/x-common/blob/master/proverb.yml))
- [ ] pythagorean-triplet ([md](https://github.com/exercism/x-common/blob/master/pythagorean-triplet.md), [yml](https://github.com/exercism/x-common/blob/master/pythagorean-triplet.yml))
- [ ] queen-attack ([md](https://github.com/exercism/x-common/blob/master/queen-attack.md), [yml](https://github.com/exercism/x-common/blob/master/queen-attack.yml))
- [ ] robot-simulator ([md](https://github.com/exercism/x-common/blob/master/robot-simulator.md), [yml](https://github.com/exercism/x-common/blob/master/robot-simulator.yml))
- [ ] saddle-points ([md](https://github.com/exercism/x-common/blob/master/saddle-points.md), [yml](https://github.com/exercism/x-common/blob/master/saddle-points.yml))
- [ ] say ([md](https://github.com/exercism/x-common/blob/master/say.md), [yml](https://github.com/exercism/x-common/blob/master/say.yml))
- [ ] secret-handshake ([md](https://github.com/exercism/x-common/blob/master/secret-handshake.md), [yml](https://github.com/exercism/x-common/blob/master/secret-handshake.yml))
- [ ] sgf-parsing ([md](https://github.com/exercism/x-common/blob/master/sgf-parsing.md), [yml](https://github.com/exercism/x-common/blob/master/sgf-parsing.yml))
- [ ] simple-cipher ([md](https://github.com/exercism/x-common/blob/master/simple-cipher.md), [yml](https://github.com/exercism/x-common/blob/master/simple-cipher.yml))
- [ ] simple-linked-list ([md](https://github.com/exercism/x-common/blob/master/simple-linked-list.md), [yml](https://github.com/exercism/x-common/blob/master/simple-linked-list.yml))
- [ ] sublist ([md](https://github.com/exercism/x-common/blob/master/sublist.md), [yml](https://github.com/exercism/x-common/blob/master/sublist.yml))
- [ ] trinary ([md](https://github.com/exercism/x-common/blob/master/trinary.md), [yml](https://github.com/exercism/x-common/blob/master/trinary.yml))
- [ ] twelve-days ([md](https://github.com/exercism/x-common/blob/master/twelve-days.md), [yml](https://github.com/exercism/x-common/blob/master/twelve-days.yml))
- [ ] wordy ([md](https://github.com/exercism/x-common/blob/master/wordy.md), [yml](https://github.com/exercism/x-common/blob/master/wordy.yml))
- [ ] zipper ([md](https://github.com/exercism/x-common/blob/master/zipper.md), [yml](https://github.com/exercism/x-common/blob/master/zipper.yml))

**Comment by outkaj** [comment]
I'd be willing to assist with porting the remaining exercises to Python if there's still interest in doing so.

**Comment by kytrinyx** [comment]
Thank you -- yes! We're always looking to improve the existing tracks both in terms of making problems better and adding new problems.

The problem API contributing guide has a good overview of how the language tracks are put together: github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by outkaj** [comment]
I put together a list of unimplemented exercises. Let me know if I am missing anything. I will also investigate to see if any are foregone for Python, but it looks like that's unlikely given the discussion above.

bank-account
binary-search-tree
bottles
clock
connect
custom-set
dot-dsl
food-chain
forth
go-counting
linked-list
list-ops
parallel-letter-frequency
pig-latin
robot-simulator
saddle-points
sgf-parsing
simple-linked-list
zipper

**Comment by kytrinyx** [comment]
That list looks good.

There aren't any foregone exercises in python: https://github.com/exercism/xpython/blob/master/config.json#L68

**Comment by Dog** [comment]
Saw in the xocaml track that we can now hit an endpoint to see what problems need to be implemented. It is the ToDo key:

http://x.exercism.io/tracks/python

**Comment by bkarlovitz** [comment]
Are the exercises in the list from @outkaj (three comments up) to be implemented? I'd be happy to do a few. @kytrinyx

**Comment by behrtam** [comment]
Sure go ahead, but maybe start with one instead of *a few* in parallel. If you need any help or some feedback, join the gitter dev channel or just open an issue or a PR (even if the exercise is not ready). There are many people happy to help.

The exercises in the todo list right now are: 
- [ ] alphametics
- [ ] bank-account
- [ ] binary-search-tree
- [ ] binary-search
- [ ] bowling
- [ ] change
- [ ] clock
- [ ] connect
- [ ] counter
- [ ] custom-set
- [ ] diffie-hellman
- [ ] dominoes
- [ ] dot-dsl
- [ ] error-handling
- [ ] food-chain
- [ ] forth
- [ ] go-counting
- [ ] grep
- [ ] hangman
- [ ] ledger
- [ ] lens-person
- [ ] nucleotide-codons
- [ ] paasio
- [ ] parallel-letter-frequency
- [ ] perfect-numbers
- [ ] pov
- [ ] protein-translation
- [ ] react
- [ ] scale-generator
- [ ] sgf-parsing
- [ ] simple-linked-list
- [ ] tournament
- [ ] tree-building
- [ ] two-bucket
- [ ] word-search
- [ ] zipper

**Comment by bkarlovitz** [comment]
@behrtam Thanks :) I'll start with one.

**Comment by kytrinyx** [comment]
We have a new process that you can use to find exercises to implement.
You can read all about it [here](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track).

I'm closing this issue in favor of the process described in the Contributing guide linked to above.

Thanks!
