### ISSUE TITLE
Add monitoring of dependencies

### ISSUE THREAD

**Issue by behrtam** [exercism/xpython#306]
To avoid manually checking for changed dependencies, now that we introduced version pinning (#305), maybe we could use https://requires.io to do that for us. As you can see in my [fork](https://requires.io/github/behrtam/xpython/requirements/?branch=travis-version-pinning) the versions are extracted successfully.

There are three ways to get notified:

- include a badge into our readme [![Requirements Status](https://requires.io/github/behrtam/xpython/requirements.svg?branch=travis-version-pinning)](https://requires.io/github/behrtam/xpython/requirements/?branch=travis-version-pinning)
- email notifications
- automatic pull request

As we only use those packages for testing my feeling is that the badge is sufficient and maybe emails to the track maintainers. It is free for public repos but it can only be activated by administrators.

**Comment by kytrinyx** [comment]
I'd be happy to activate it. Ill take a look at it today.

**Comment by kytrinyx** [comment]
OK, I think that should work.

**Comment by behrtam** [comment]
Thank you.
