### ISSUE TITLE
bob_test doesn't fully test bob specification

### ISSUE THREAD

**Issue by matts-code** [exercism/xpython#312]
The bob test suite doesn't test the case of ending a non-question statement with whitespace.  You can see that by this code passing all given tests, but failing if a test case of a statement with trailing whitespace is given.

```
from string import letters

def hey(what):

    if not what or what.isspace():
    	return "Fine. Be that way!"

    elif what == what.upper() and not set(letters).isdisjoint(set(what)):
    	return "Whoa, chill out!"

    elif what.endswith(("?"," ")):
    	return "Sure."

    return "Whatever."
```

An example test case is 

```
def test_non_question_ends_with_whitespace(self):
        self.assertEqual(
            'Whatever.', bob.hey('This is a statement with trailing whitespace   ')
        )
```

**Comment by kytrinyx** [comment]
Would you be interested in submitting a patch for this?

We have common test inputs/outputs in the x-common repository: https://github.com/exercism/x-common/blob/master/bob.json -- I don't think we have this test case in there, either.

**Comment by matts-code** [comment]
Sure. I'm working on it now.

**Comment by kytrinyx** [comment]
Thanks!

**Comment by behrtam** [comment]
@matts-code do you need any help?

**Comment by patricksjackson** [comment]
Just to ping this thread, it looks like @matts-code contributed this additional test case to x-common (exercism/x-common#186) but since we don't automatically generate the test suite for python it needs to be added here as well.

It's probably safe to assume he's not coming back to add it at this point. I'd be happy to put it together if you want.

**Comment by Dog** [comment]
@patricksjackson Sure, I'm hoping to go through the pull requests in the next couple of days to try to resolve the backlog we have going on. If you'd like to take the issue, let me know and I'll hold off.
