### ISSUE TITLE
Workflow is missing on exercism.io

### ISSUE THREAD

**Issue by k4rtik** [exercism/xpython#315]
There used to be a workflow section in Python language documentation on the main website containing https://github.com/exercism/xpython/blob/master/docs/WORKFLOW.md, it's gone now.

**Comment by kytrinyx** [comment]
Ah, this file should have been renamed--but I missed it. I'll fix that now.

Thanks for catching it!

**Comment by kytrinyx** [comment]
Both files exist. Can you tell if I should just copy workflow -> tests, or do we need to carefully merge the content?

**Comment by k4rtik** [comment]
@kytrinyx I hope that question is not for me, I do not know. I noticed this as I had referred to it when I started practicing python last July, dropped it and continued again couple weeks ago.

**Comment by kytrinyx** [comment]
It was :) But "nope" is a totally fair answer.

I'll see if I can sort it out.

**Comment by behrtam** [comment]
So we need to merge `TESTS.md` and `WORKFLOW.md`? If you don't want to look into it, I can try to figure that one out later this day.

**Comment by kytrinyx** [comment]
Yepp, we need to merge `TESTS.md` and `WORKFLOW.md` into just `TESTS.md`.

That would be great, @behrtam, thanks! If you don't get to it, it'll be on my list.
