### ISSUE TITLE
Verify "Largest Series Product" exercise implementation

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xpython#317]
There was some confusion in this exercise due to the ambiguous use of the term _consecutive_ in the README. This could be taken to mean _contiguous_, as in consecutive by position, or as in _consecutive numerically_. The the README has been fixed (https://github.com/exercism/x-common/pull/200).

**Please verify that the exercise is implemented in this track correctly** (that it finds series of contiguous numbers, not series of numbers that follow each other consecutively).

If it helps, the canonical inputs/outputs for the exercise can be found here:
https://github.com/exercism/x-common/blob/master/largest-series-product.json

If everything is fine, go ahead and just close this issue. If there's something to be done, then please describe the steps needed in order to close the issue.

**Comment by behrtam** [comment]
The implementation was/is correct, but we were missing some standard test cases.
