### ISSUE TITLE
Pass explicit list of multiples in "Sum of Multiples" exercise rather than defaulting to 3 and 5

### ISSUE THREAD

**Issue by petertseng** [exercism/xpython#319]
Hello, as part of https://github.com/exercism/x-common/issues/198 we'd like to make the sum of multiples exercise less confusing. Currently, the [README](https://github.com/exercism/x-common/blob/master/sum-of-multiples.md) specifies that if no multiples are given it should default to 3 and 5.

We'd like to remove this default, so that a list of multiples will always be specified by the caller. This makes the behavior explicit, avoiding surprising behavior and simplifying the problem.

**Please make sure this track's tests for the sum-of-multiples problem do not expect such a default**. Any tests that want to test behavior for multiples of [3, 5] should explicitly pass [3, 5] as the list of multiples.

After all tracks have completed this change, then https://github.com/exercism/x-common/pull/209 can be merged to remove the defaults from the README.

The reason we'd like this change to happen before changing the README is that it was very confusing for students to figure out the default behavior. It wasn't clear from simply looking at the tests that the default should be 3 and 5, as seen in https://github.com/exercism/exercism.io/issues/2654, so some had to resort to looking at the example solutions (which aren't served by `exercism fetch`, so they have to find it on GitHub). It was added to the README to fix this confusion, but now we'd like to be explicit so we can remove the default line from the README.

You can find the common test data at https://github.com/exercism/x-common/blob/master/sum-of-multiples.json, in case that is helpful.

**Comment by kotp** [comment]
This should be closed, due to the merge of #327 and this will also signal to exercism/x-common#198 that this is done.

**Comment by petertseng** [comment]
excellent, many thanks.
