### ISSUE TITLE
Grade school test is imposing unnecessary restrictions on implementations

### ISSUE THREAD

**Issue by de2Zotjes** [exercism/xpython#322]
The tests for the grade school exercise assert against an attribute of the class to implement. This imposes restrictions on the name and type of the attribute. Elsewhere in the testsuite the data is accessed via the 'grade' method, that is possible for all tests.

**Comment by kytrinyx** [comment]
That's a good observation. We've seen this problem in a number of different language tracks, and have slowly been improving the test suite to allow a wider variety of approaches in the solutions.

**Comment by de2Zotjes** [comment]
Since you agree this is an issue I have taken the liberty to create what I think is an improved set of tests for the grade-school exercise
