### ISSUE TITLE
missing/incorrect command 

### ISSUE THREAD

**Issue by johnjullies** [exercism/xpython#332]
On "Installing pytest" on http://exercism.io/languages/python, the first command is `pip install` which should be `pip install pystest`.

**Comment by behrtam** [comment]
Good catch! That somehow got lost in a merge 20 days ago ...
https://github.com/exercism/xpython/commit/ffa11c6f2c4ef46cf5cf5501968968128b458a15#diff-40736f68964f825efc4f1d54bfc3ab51L5
