### ISSUE TITLE
not an issue but a doubt

### ISSUE THREAD

**Issue by iamharshit** [exercism/xpython#335]
please explain the meaning of the word `-teenth` in the exercise http://exercism.io/exercises/python/meetup/readme ,it isn't clear as described

**Comment by kytrinyx** [comment]
"teenth" is the suffix given to many of the numbers between 10 and 20 in English in its ordinal form.

First, second, third, ..., thirteenth, fourteenth, fifteenth, etc.

**Comment by iamharshit** [comment]
i got it

**Comment by iamharshit** [comment]
@kytrinyx 
Just wanted an advice, if we got stuck at a problem in that case what should we do ?

**Comment by kytrinyx** [comment]
You could try the support chat channel http://gitter.im/exercism/support or post the solution you have with a comment explaining where you're stuck:

```
exercism submit mysolution.py -comment="What does teenth mean? The README wasn't clear
on this and I couldn't find it in the dictionary."
```
