### ISSUE TITLE
No 'year' module to import for use in test for xpython: leap exercise

### ISSUE THREAD

**Issue by rachelkelly** [exercism/xpython#336]
Test failure because could not find `year` module to import.  I located another appropriate module to import: `calendar` with method `isleap` for purposes of testing.

Running Python 2.7.10, native install on OSX 10.11.4.

I place as an issue rather than PR because a) unsure how to test for inclusion with Python >= 3.3 and b) if user needs to use a different version of Python then that should be explicitly stated elsewhere and is outside the scope of this issue and c) if user needs a particular module outside typical access that should be stated and instructed in the exercise.

Altered test file below:

```
# leap_test.py

import unittest

from calendar import isleap


class YearTest(unittest.TestCase):
    def test_leap_year(self):
        self.assertIs(isleap(1996), True)

    def test_non_leap_year(self):
        self.assertIs(isleap(1997), False)

    def test_non_leap_even_year(self):
        self.assertIs(isleap(1998), False)

    def test_century(self):
        self.assertIs(isleap(1900), False)

    def test_exceptional_century(self):
        self.assertIs(isleap(2400), True)

if __name__ == '__main__':
    unittest.main()
```

**Comment by rachelkelly** [comment]
I see that the test file has certain expectations of the function name and the file name.  This should be made explicit and I will submit a PR

**Comment by kytrinyx** [comment]
Hi @rachelkelly, thanks for this!

I'm not familiar with the Python track, but my immediate thought is that the `leap` module is not an existing module that people would import from somewhere, but rather that it's the module that they would write as a solution to this. If this is the case and it's confusing, then we probably need to document this better.
