### ISSUE TITLE
Sublist tests pass with no implementation

### ISSUE THREAD

**Issue by IanWhitney** [exercism/xpython#342]
http://exercism.io/submissions/bc21579f3bf54f6d99a39093d8396157

A member of my Kata group reports that all tests pass with that implementation. It's, uh, very concise. But I don't think it's accurate.

**Comment by patricksjackson** [comment]
The simple fix for this is an extra test for checking for unique return values, so I threw together the pull request for that.

That implementation above still passes all the other tests, so there may be a better way to do it.
