### ISSUE TITLE
requires.io badge incorrectly outdated

### ISSUE THREAD

**Issue by behrtam** [exercism/xpython#376]
The requires.io badge [Requirements Status](https://requires.io/github/exercism/xpython/requirements/?branch=master) still shows as outdated. Somehow it doesn't reflect the changes #363 in the `requirements-travis.txt`.

**Comment by behrtam** [comment]
So I wrote to their support ...

> Indeed we have a problem: there seem to be no user with valid credentials to access this repository, so all our queries towards GitHub are rejected.
> 
> The best way to solve this would be to log into requires with a user with admin access to this repository, and deactivate it/reactivate it again.
> 
> You may have to do the following:
> - log into GitHub,
> - go to the applications settings (https://github.com/settings/applications),
> - select requires.io,
> - in Organization access, grant access to exercism,
> - go back to your requires.io settings: https://requires.io/settings/repositories/
> - wait for it to recover all the repositories,
> - deactivate and reactivate all the repositories you want to track.

Sorry @kytrinyx that I have to bother you again with this. Maybe a last try if this service fails again, we can just remove it.

**Comment by kytrinyx** [comment]
Aaah, I missed this. I'll try to get this sorted this weekend.

**Comment by behrtam** [comment]
With the update of the requirements #399 and the restart it looks good/green again. Thanks!

**Comment by kytrinyx** [comment]
Awesome, thanks for chasing that down and explaining exactly what I needed to do to get it fixed. It made it very easy.
