### ISSUE TITLE
Investigate track health and status of the track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xpython#395]
I've used Sarah Sharp's [FOSS Heartbeat](https://github.com/sarahsharp/foss-heartbeat) project to generate stats for each of the language track repositories, as well as the x-common repository.

The Exercism heartbeat data is published here: https://exercism.github.io/heartbeat/

When looking at the data, please disregard any activity from me (`kytrinyx`), as I would like to get the language tracks to a point where they are entirely maintained by the community.

Please take a look at the heartbeat data for this track, and answer the following questions:

* To what degree is the track maintained?
* Who (if anyone) is merging pull requests?
* Who (if anyone) is reviewing pull requests?
* Is there someone who is not merging pull requests, but who comments on issues and pull requests, has thoughtful feedback, and is generally helpful? If so, maybe we can invite them to be a maintainer on the track.

I've made up the following scale:

* **ORPHANED** - Nobody (other than me) has merged anything in the past year.
* **ENDANGERED** - Somewhere between ORPHANED and AT RISK.
* **AT RISK** - Two people (other than me) are actively discussing issues and reviewing and merging pull requests.
* **MAINTAINED** - Three or more people (other than me) are actively discussing issues and reviewing and merging pull requests.

It would also be useful to know if there a lot of activity on the track, or just the occasional issue or comment.

Please report the current status of the track, including your best guess on the above scale, back to the top-level issue in the discussions repository: https://github.com/exercism/discussions/issues/97

**Comment by behrtam** [comment]
https://github.com/exercism/discussions/issues/97#issuecomment-261892107
