### ISSUE TITLE
Python version support: 3.3 or 3.5?

### ISSUE THREAD

**Issue by rootulp** [exercism/xpython#407]
The [README](https://github.com/exercism/xpython/blob/master/README.md) states: 

> All exercises must be compatible with Python versions 2.7 and 3.3 upwards. Therefore please test your changes at least with Python2.7 and Python3.5.

I'm confused. Should we test with Python**3.3** or Python**3.5**? If all exercises must be compatible with 3.3 upwards should we instruct users to test with Python3.3 instead?

**Comment by behrtam** [comment]
Our CI build is [configured](https://github.com/exercism/xpython/blob/master/.travis.yml#L6-L10) to test with Python 2.7, 3.3, 3.4 ... and the exercises also run with 3.2 or 2.6 I guess. So, the user should just use what ever Python he or she has. If they don't have Python installed, they should probably head for the latest 3.X version.

Contributors to this track should make sure that we support as many versions as possible. So, I normally test for 2.7 and 3.6 locally and let the CI server check the rest.

**Comment by rootulp** [comment]
> So, I normally test for 2.7 and 3.6 locally and let the CI server check the rest.

Would you mind if I updated the README to reflect this?

**Comment by behrtam** [comment]
That would be great. Maybe we can find a way so that we don't need to change the readme every time we get a new Python release.

**Comment by rootulp** [comment]
I think this depends on what versions of Python we want to officially support. If we commit to supporting Python 2.7 and 3.3 and upwards I think it makes sense to instruct contributors to test with those versions. Our CI builds can continue to check for later versions of Python 3.X which I would expect to reasonably pass given they pass 3.3.
