### ISSUE TITLE
list-ops test case for mixed types

### ISSUE THREAD

**Issue by richardgiddings** [exercism/xpython#414]
In the list-ops Python exercise there is a test test_reverse_mixed_types that tests a tuple. Should we have this test if we are writing list operations?

**Comment by behrtam** [comment]
I don't fully understand your question. What do you mean by "should we have this test"? Do you mean it should be removed or are you asking if your code should fulfill that test?

**Comment by richardgiddings** [comment]
Sorry it wasn't clear. I thought the test should be removed as it is testing tuples rather than lists.

**Comment by behrtam** [comment]
Yes, the test suite for this exercise definitely needs to be improved. It's not only this one test case: #413

**Comment by richardgiddings** [comment]
I see, I would say in that case to change test_reverse_empty to:

def test_reverse_empty(self):
    self.assertEqual([], list_ops.reverse([]]))

and remove the test case test_reverse_mixed_types.

I think there are also some unnecessary calls to tuple() but I don't think they affect the purpose of the tests as they are not passing tuples to the list_ops functions.

There is also an argument for changing the name test_append_tuple to something like test_append_to_list.

**Comment by richardgiddings** [comment]
Also test_pos_leng could pass a list instead of a tuple.

**Comment by behrtam** [comment]
Now with #413 merged, everything should be about lists.
