### ISSUE TITLE
Inconsistency in Kindergarten Garden exercise

### ISSUE THREAD

**Issue by dzhoshkun** [exercism/xpython#423]
The [problem description][prob] says there are 12 children in the class (named Alice through Larry), however the [test suite includes a test with other names][test30]. This is a bit confusing. I think it would be better to keep the README and the test suite consistent.

[prob]: https://github.com/exercism/x-common/blob/master/exercises/kindergarten-garden/description.md
[test30]: https://github.com/exercism/xpython/blob/master/exercises/kindergarten-garden/kindergarten_garden_test.py#L30

**Comment by cmlang42** [comment]
Agreed. The problem description does list the "children in the class" and the "disordered test" specifies names that are not on that class list. I propose to change the disordered test to use names from the list in the problem description.

@behrtam - I would like to work on this issue.

**Comment by behrtam** [comment]
We should work on this at the `x-common` level first.

**Comment by behrtam** [comment]
https://github.com/exercism/x-common/pull/770
