### ISSUE TITLE
Hello-World just a bit over a newbie level?

### ISSUE THREAD

**Issue by cmlang42** [exercism/xpython#430]
Just thinking a bit about the Hello-World exercise for Python and that it might be a bit above a complete newbie level. In order for a few of the tests to pass an if statement is needed to test the incoming value. While this is low level material, I recommend that maybe it be more simple to have the function simply return the "Hello, World!" string.

**Comment by behrtam** [comment]
You are not the first or only one that thinks that way. It should change in the future: https://github.com/exercism/x-common/issues/520

**Comment by cmlang42** [comment]
Thanks @behrtam!
