### ISSUE TITLE
Parameter order in assertEqual() statements

### ISSUE THREAD

**Issue by behrtam** [exercism/xpython#440]
We have both ways of ordering the parameters actual, expected result of the `assertEqual()` method. 

While the Python implementation uses indifferent names (first, second - [code](https://github.com/python/cpython/blob/master/Lib/unittest/case.py#L816)) all examples use the order actual followed by expected ([python doc – basic-example](https://docs.python.org/3/library/unittest.html#basic-example)).
```python
self.assertEqual('foo'.upper(), 'FOO')
self.assertEqual(s.split(), ['hello', 'world'])
```
I think it would be better to be consistent within this track. As I personally don't have any preferences I would just follow the official python documentation examples and default to `self.assertEqual(actual, expected)`.

@rootulp @pheanex do you have any opinions about this?

**Comment by pheanex** [comment]
(actual, expected) looks good to me. I am in favour of consistency.

**Comment by rootulp** [comment]
I think conforming to the Python doc basic example is a god idea. (Actual, expected) seems right.

**Comment by nikclayton** [comment]
FYI -- if you run the tests in PyCharm (as I'm doing with my students) PyCharm shows the Expected/Actual results in the wrong order. The JetBrains bug for this behaviour is https://youtrack.jetbrains.com/issue/PY-27267.

**Comment by cmccandless** [comment]
@nikclayton thank you for adding that info here.

We've run into that issue before here, but it's good to document it as a known issue.
