### ISSUE TITLE
Update grains exercise (tests and example)

### ISSUE THREAD

**Issue by behrtam** [exercism/xpython#450]
The exercise **grains** is missing some exception tests that are part of the canonical test data.
https://github.com/exercism/x-common/blob/master/exercises/grains/canonical-data.json#L55-L72

To add those tests the example implementation also needs to be updated. This task might be similar to the changes done in PR 439: https://github.com/exercism/xpython/pull/439/files

**Comment by cmlang42** [comment]
I will take a look at this.
