### ISSUE TITLE
convert to assert-based tests?

### ISSUE THREAD

**Issue by catherinedevlin** [exercism/xpython#464]
Since the instructions suggest running the tests with `py.test` anyway, there's no need to use heavyweight `unittest`-based tests.  `py.test` supports simple `assert` tests, which I think would be much clearer and less intimidating for new programmers to understand.

For example, `hello_world_test.py` could be slimmed down to
```
import hello_world

def test_hello_world():
    assert hello_world.hello() == 'Hello, World!'
```

... unless there's some exercism-specific reason not to do so?  

If appropriate, I'd be happy to submit the pull requests - I just don't want to charge ahead if there's a reason for the unittest-based ones.

**Comment by behrtam** [comment]
While we suggest to use `py.test` it would actually be interesting to know how many people really install it or just stick to the built-in stuff.

Every exercise can be solved without the need to install 3rd party packages. The same is true for the tests, we even make sure that it runs on 2.7, 3.3, 3.4, ... because many people can't or don't know how to install another python version.

Without any real usage data, I think it's hard to justify a switch that would require people to install 3rd party packages.

**Comment by behrtam** [comment]
Do you really think the difference is so huge that it would be worth to force everyone to install `py.test` even if most of the people already run `py.test`? We would save 4 lines per test file (import, class, run main) and sometimes have a nicer simpler assert line and in other cases, it maybe isn't  really simpler.

A – unittest
```python
import unittest
import hello_world

class HelloWorldTests(unittest.TestCase):
  def test_hello(self):
    self.assertEqual(hello_world.hello(), 'Hello, World!')

if __name__ == '__main__':
    unittest.main()
```
A – unittest
```python
import hello_world

def test_hello_world():
  assert hello_world.hello() == 'Hello, World!'
```

B - unittest
```python
def test_allergic_to_lots_of_stuff(self):
  self.assertCountEqual(
    Allergies(248).lst,
    ['strawberries', 'tomatoes', 'chocolate', 'pollen', 'cats'])
```

B - py.test
```python
def test_allergic_to_lots_of_stuff():
  assert sorted(
    Allergies(248).lst
  ) == ['cats', 'chocolate', 'pollen', 'strawberries', 'tomatoes']
```

C – unittest
```python
def test_two_different_books(self):
        self.assertAlmostEqual(calculate_total([1, 2]), 15.20, places=2)
```

C - py.test
```python
def test_two_different_books():
        assert round(calculate_total([1, 2]), 2) == round(15.2, 2)
```

**Comment by behrtam** [comment]
The difference is very small and there are many people that don't use `py.test` ([survey](https://gist.github.com/behrtam/9b1aaae227b5e67dd145ecd5f74e58eb)).
