### ISSUE TITLE
meetup: incorrect test

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xpython#476]
@Ef-Eff reported in https://github.com/exercism/exercism.io/issues/3552:

The last test for the Python challenge  Meetup is written incorrectly, it is simply missing the parentheses for the function after the exception. 
This:
`def test_nonexistent_fifth_monday_of_february_2015(self):
        self.assertRaises(MeetupDayException, meetup_day, 2015, 2, 'Monday',
                          '5th')`
Should be this:
`def test_nonexistent_fifth_monday_of_february_2015(self):
        self.assertRaises(MeetupDayException, meetup_day(2015, 2, 'Monday',
                          '5th'))`

After making this change, the test worked as intended.

-------

@catb0t noted:

[this](https://github.com/exercism/xpython/blob/master/exercises/meetup/meetup_test.py#L401) is the relevant line and file, and [0d6d90f](https://github.com/exercism/xpython/commit/0d6d90faddad9ad48d226441884a25796879018a)  introduced it.

-----

Here's our documentation about exercise test suites on Exercism in general:
https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/exercise-test-suites.md

Check out the README and CONTRIBUTING guide in this repository to check for considerations specific to Python.

**Comment by behrtam** [comment]
It is written correctly as it is right now.

If you take a look at the python docs ([see this](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises)) you will see that `assertRaises(exception, callable, *args, **kwds)` takes a callable and than the arguments for that. This way you don't actually call the function your self.

While it's correct, I still think we could improve it. There is another way to test exceptions added with Python 2.7. If you use a context manger instead you can make the call your self which makes it more understandable/explicit, but they do (test) exactly the same thing.

```python
def test_it(self):
    self.assertRaises(SomeException, do_something, 42, True)

def test_it_with_context(self):
    with self.assertRaises(SomeException):
        do_something(42, True)
```
